name: QA & sanity checks
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  quality:
    name: Code sanity
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y curl ca-certificates git
      - uses: actions/checkout@v5
      - name: Go code sanity check
        uses: canonical/desktop-engineering/gh-actions/go/code-sanity@v2
        with:
          golangci-lint-configfile: ".golangci-ci.yaml"
          tools-directory: "tools"
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run tests
        run: |
          go test -coverpkg=./... -coverprofile=/tmp/coverage.tmp -covermode=count ./...

          # Exclude testutils and generated files from the final coverage report
          grep -hv -e "testutils" -e "_string\.go" /tmp/coverage.tmp > /tmp/coverage.out
      - name: Run tests (with race detector)
        run: |
          go test -race ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: /tmp/coverage.out
